# Generated by Django 5.2.4 on 2025-07-06 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peran', models.CharField(choices=[('arsitek', 'Arsitek'), ('mandor', 'Mandor')], max_length=10)),
                ('nomor_telepon', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_proyek', models.CharField(max_length=200)),
                ('lokasi', models.CharField(max_length=255)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('arsitek', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyek_arsitek', to=settings.AUTH_USER_MODEL)),
                ('mandor_bertugas', models.ManyToManyField(blank=True, related_name='proyek_mandor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dokumen', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='dokumen/%Y/%m/%d/')),
                ('tanggal_unggah', models.DateTimeField(auto_now_add=True)),
                ('diunggah_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='perancangan.proyek')),
            ],
        ),
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tugas', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('belum', 'Belum Dikerjakan'), ('dikerjakan', 'Sedang Dikerjakan'), ('selesai', 'Selesai'), ('revisi', 'Butuh Revisi')], default='belum', max_length=20)),
                ('mandor_penanggung_jawab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tugas_mandor', to=settings.AUTH_USER_MODEL)),
                ('proyek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas', to='perancangan.proyek')),
            ],
        ),
        migrations.CreateModel(
            name='LaporanKemajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.TextField()),
                ('foto_kemajuan', models.ImageField(blank=True, null=True, upload_to='laporan/%Y/%m/%d/')),
                ('tanggal_laporan', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='perancangan.tugas')),
            ],
        ),
    ]
